### ISSUE TITLE
Cannot open chat tab settings

### ISSUE THREAD

**Issue by Kladki** [ebicep/ChatPlus#74]
### Describe your issue

I cannot click to open the individual chat (auto) tabs to edit them

### MC/Loader/ChatPlus Version

MC: 1.21.4
Fabric: 0.16.10
Chat Plus: 2.4.0

### If applicable, add screenshots to help explain your problem.

https://github.com/user-attachments/assets/613824d0-d560-4553-b24d-ee87d6e373b3

### If applicable, upload your config file to help reproduce the issue, name of config is latest possible version.

The name was `chatplus-v2.1.0.json`

```
{
    "enabled": true,
    "addMessagesIfDisabled": false,
    "showVanillaWhenUnfocused": false,
    "vanillaInputBox": false,
    "saveInputBoxMessage": false,
    "wrappedMessageLineIndent": 0,
    "maxMessages": 1000,
    "maxCommandSuggestions": 15,
    "jumpToMessageMode": "CURSOR",
    "selectChatLinePriority": 100,
    "timestampSettings": {
        "enabled": true,
        "timestampFormat": "&7Sent at &e{hh:mm:ss a}&7.",
        "chatTimestampModeType": "HOVER"
    },
    "inputOverFlowAutoFillSettings": {
        "enabled": true,
        "onlyOnEnter": true,
        "clearQueueIfCloseOnEmpty": true,
        "autoFillCommandInteraction": "IGNORE",
        "queueMode": "OVERWRITE"
    },
    "hideChatEnabled": false,
    "hideChatShowWhenFocused": true,
    "hideChatShowHiddenOnScreen": true,
    "hideChatToggleKey": {
        "key": "key.keyboard.unknown",
        "modifier": 0
    },
    "alwaysShowChat": false,
    "alwaysShowChatToggleKey": {
        "key": "key.keyboard.unknown",
        "modifier": 0
    },
    "compactMessagesEnabled": true,
    "compactMessagesRefreshAddedTime": false,
    "compactMessagesSearchAmount": 1,
    "compactMessageComparatorMode": "VANILLA",
    "compactMessageSettings": {
        "ignoreTimestamps": true,
        "contents": true,
        "style": true,
        "styleSettings": {
            "color": true,
            "bold": true,
            "italic": true,
            "underlined": true,
            "strikethrough": true,
            "obfuscated": true,
            "clickEvent": true,
            "hoverEvent": true,
            "insertion": true,
            "font": true
        }
    },
    "scrollbarEnabled": false,
    "invertedScrolling": false,
    "scrollbarColor": -8354165,
    "scrollbarWidth": 6,
    "animationEnabled": true,
    "animationDisableOnFocus": false,
    "animationNewMessageTransitionTime": 200,
    "scrollCycleTabEnabled": true,
    "arrowCycleTabEnabled": true,
    "moveToTabWhenCycling": true,
    "tabNotificationSettings": {
        "enabled": true,
        "scale": 0.4
    },
    "chatWindows": [
        {
            "generalSettings": {
                "disabled": false,
                "backgroundColor": -2147483648,
                "unfocusedBackgroundColorOpacityMultiplier": 0.0,
                "scale": 1.0,
                "textOpacity": 1.0,
                "textShadow": true,
                "unfocusedTextOpacityMultiplier": 1.0,
                "unfocusedHeight": 0.5,
                "lineSpacing": 0.0,
                "messageAlignment": "LEFT",
                "messageDirection": "BOTTOM_UP"
            },
            "outlineSettings": {
                "enabled": false,
                "showWhenChatNotOpen": false,
                "outlineColor": 0,
                "unfocusedOutlineColorOpacityMultiplier": 0.39999998,
                "outlineBoxType": "TEXT_BOX",
                "outlineTabType": "SELECTED_TAB_OPEN_TOP"
            },
            "padding": {
                "left": 0,
                "right": 0,
                "bottom": 0
            },
            "renderer": {
                "x": 0,
                "y": -29,
                "width": 281,
                "height": 441
            },
            "tabSettings": {
                "selectedTabIndex": 0,
                "startRenderTabIndex": 0,
                "hideTabs": false,
                "showTabsWhenChatNotOpen": false,
                "tabTextColorSelected": -1,
                "tabTextColorUnselected": -6710887,
                "unfocusedTabOpacityMultiplier": 0.39999998,
                "tabs": [
                    {
                        "pattern": "(?s).*",
                        "formatted": false,
                        "name": "All",
                        "autoPrefix": "",
                        "serverTabPatterns": [],
                        "priority": 0,
                        "alwaysAdd": true,
                        "skipOthers": false,
                        "commandsOverrideAutoPrefix": true,
                        "temporary": false
                    },
                    {
                        "pattern": "Party > .*",
                        "formatted": false,
                        "name": "Party",
                        "autoPrefix": "/pchat ",
                        "serverTabPatterns": [],
                        "priority": 0,
                        "alwaysAdd": false,
                        "skipOthers": false,
                        "commandsOverrideAutoPrefix": true,
                        "temporary": false
                    }
                ]
            },
            "autoTabCreator": {
                "autoTabOptions": [
                    {
                        "pattern": "(From|To) (\\w+):\\s(.*)",
                        "formatted": false,
                        "skipOthersOnCreation": true,
                        "tabNameFormatter": "%GROUP_2%",
                        "regexFormatter": "(From|To) %GROUP_2%:\\s(.*)",
                        "autoPrefixFormatter": "/msg %GROUP_2% ",
                        "priority": 0,
                        "alwaysAdd": false,
                        "skipOthers": false,
                        "commandsOverrideAutoPrefix": true,
                        "temporary": true
                    },
                    {
                        "pattern": "\\[((You -> (\\w+))|((\\w+) -> You))\\] .*",
                        "formatted": false,
                        "skipOthersOnCreation": true,
                        "tabNameFormatter": "%GROUP_3%%GROUP_5%",
                        "regexFormatter": "\\[((You -> %GROUP_3%%GROUP_5%)|(%GROUP_3%%GROUP_5% -> You))\\] .*",
                        "autoPrefixFormatter": "/msg %GROUP_3%%GROUP_5% ",
                        "priority": 0,
                        "alwaysAdd": false,
                        "skipOthers": false,
                        "commandsOverrideAutoPrefix": true,
                        "temporary": true
                    }
                ]
            }
        }
    ],
    "movableChatEnabled": false,
    "movableChatShowEnabledOnScreen": true,
    "movableChatToggleKey": "key.keyboard.right.control",
    "movableChatColor": -922746881,
    "movableChatSelectedColor": -939458816,
    "movableChatToggleTextBarElement": false,
    "sendNoteEnabled": true,
    "sendNoteKey": {
        "key": "key.keyboard.enter",
        "modifier": 4
    },
    "sendNoteClickMode": "APPEND_INPUT",
    "sendNoteSelectMode": "LINE",
    "sendNoteSelectKey": "key.keyboard.left.shift",
    "sendNoteSelectModeKey": "WHOLE_MESSAGE",
    "sendNoteTextBarElementEnabled": true,
    "filterMessagesEnabled": true,
    "filterMessagesLinePriority": 150,
    "filterMessagesPatterns": [],
    "hoverHighlightEnabled": true,
    "hoverHighlightLinePriority": 0,
    "hoverHighlightMode": "BRIGHTER",
    "hoverHighlightColor": 419430400,
    "bookmarkEnabled": true,
    "bookmarkLinePriority": 30,
    "bookmarkColor": -925260989,
    "bookmarkKey": {
        "key": "key.keyboard.b",
        "modifier": 2
    },
    "bookmarkTextBarElementEnabled": true,
    "bookmarkTextBarElementKey": {
        "key": "key.keyboard.b",
        "modifier": 2
    },
    "autoBookMarkPatterns": [],
    "findMessageEnabled": true,
    "findMessageLinePriority": 250,
    "findMessageHighlightInputBox": false,
    "findMessageTextBarElementEnabled": true,
    "findMessageKey": {
        "key": "key.keyboard.f",
        "modifier": 2
    },
    "copyMessageKey": {
        "key": "key.keyboard.c",
        "modifier": 2
    },
    "copyMessageLinePriority": 50,
    "copyNoFormatting": false,
    "copyMessageFormattingSymbolOverride": "",
    "copyMessageSeparator": "\n",
    "deleteMessageEnabled": true,
    "deleteMessageKey": {
        "key": "key.keyboard.d",
        "modifier": 2
    },
    "screenshotChatEnabled": true,
    "screenshotChatCopyToClipboard": true,
    "screenshotChatSaveToFile": true,
    "screenshotChatAutoUpload": true,
    "screenshotChatLinePriority": 200,
    "screenshotChatKey": {
        "key": "key.keyboard.s",
        "modifier": 2
    },
    "screenshotDefaultScreenShotMode": "CURRENT_WINDOW",
    "screenshotDefaultScreenBackgroundMode": "TRANSPARENT",
    "screenshotDefaultScreenShotWindowsMode": "SPLIT",
    "screenshotChatTextBarElementEnabled": true,
    "playerHeadChatDisplayEnabled": true,
    "playerHeadChatDisplayShowOnWrapped": false,
    "playerHeadChatDisplayOffsetNonHeadMessages": false,
    "playerHeadChatDisplayOffsetNonHeadMessagesShowOnWrapped": true,
    "keyNoScroll": "key.keyboard.left.control",
    "keyFineScroll": "key.keyboard.left.shift",
    "keyLargeScroll": "key.keyboard.left.alt",
    "keyPeekChat": "key.keyboard.z",
    "translatorEnabled": false,
    "translatorTextBarElementEnabled": true,
    "translatorRegexes": [],
    "translateTo": "Auto Detect",
    "translateSelf": "Auto Detect",
    "translateSpeak": "English",
    "translateKeepOnAfterChatClose": true,
    "translateKey": {
        "key": "key.keyboard.t",
        "modifier": 2
    },
    "translateToggleKey": {
        "key": "key.keyboard.t",
        "modifier": 2
    },
    "translateClickEnabled": true,
    "speechToTextEnabled": true,
    "speechToTextToInputBox": true,
    "speechToTextMicrophoneKey": "key.keyboard.b",
    "speechToTextQuickSendKey": "key.keyboard.enter",
    "speechToTextTranslateEnabled": false,
    "speechToTextTranslateToInputBox": true,
    "speechToTextTranslateLang": "English",
    "speechToTextSampleRate": 48000,
    "speechToTextMicrophone": "Default",
    "speechToTextSelectedAudioModel": ""
}
```

**Comment by ebicep** [comment]
Fixed in v2.4.0 (Latest).
- Made config lists expanded by default due to a bug in cloth config v17 (1.21.4)

**Comment by Kladki** [comment]
I _am_ using 2.4.0 though...

**Comment by ebicep** [comment]
Yes, I pushed a new jar, same version https://modrinth.com/mod/chat-plus/version/jQSAIYUp

**Comment by Kladki** [comment]
Ah ok. Launchers like Prism don't realise this though, since the version number is the same, so people who already updated will still have this issue unless they re-install Chat Plus btw. So it might be worth setting the version to 2.4.1 or something.
